name: hackathon
description: 黑客松桌面应用

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  provider: ^6.0.1
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2
  dio: ^4.0.0
  connectivity: ^3.0.6
  device_info: ^2.0.2
  flutter_svg: ^0.23.0+1
  webview_flutter: ^2.1.1
  permission_handler: ^8.0.0+2
  flutter_spinkit: ^5.1.0
  package_info: ^2.0.2
  crypto: ^3.0.1
  encrypt: ^5.0.0
  flutter_localizations:
    sdk: flutter
  fijkplayer: ^0.10.1
  lottie: ^1.2.1
  url_launcher: ^6.0.18
  desktop_webview_window: ^0.1.6
  system_tray: ^0.1.0
  bitsdojo_window: ^0.1.1+1
  video_player: ^2.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true
  generate: true # Add this line
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
          style: italic
  assets:
    - assets/
    - assets/icon/
    - assets/tray/
    - assets/fonts/
